# This is a basic workflow to help you get started with Actions

name: Compile LaTeX to PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - '**.tex' # Only trigger when .tex files change
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main_software.tex
          latexmk_shell_escape: true     # Enable shell escape if needed (e.g., for minted)
          latexmk_use_xelatex: true      # Use XeLaTeX (optional, remove if using pdflatex)
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          post_compile: "latexmk -c"     # Clean up temporary files
        
      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: main_software.pdf
          path: main_software.pdf  # Must match root_file name
