# This is a basic workflow to help you get started with Actions

name: Compile LaTeX to PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - '**.tex' # Only trigger when .tex files change
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main_software.tex
          args: -shell-escape -interaction=nonstopmode -file-line-error
      
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdf
          path: |
            *.pdf
            *.aux
            *.log  # Optional: include logs if needed
            
      - name: Commit PDF to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add *.pdf
          git commit -m "Auto-generated PDF from LaTeX" || echo "No changes to commit"
          git push
